djangoProject/urls.py
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings
from callapps.views import account, runGUI, recognise, user, admin, avatar, depart

urlpatterns = [
    # 默认访问用户列表页面
    # path('', user.user_list),
    path('', account.login),

    # 部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/<int:nid>/delete/', depart.depart_delete),
    path('depart/<int:nid>/edit/', depart.depart_edit),

    # 用户管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),

    # 管理员管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    # 登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    # 注册
    path('register/', account.register),

    # 上传图片
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # 头像
    path('avatar/edit/', avatar.avatar_edit),

    # runGUI
    path('recognise/', recognise.link),
    path('call/', runGUI.run)
]

callapps/models.py
from django.db import models


# Create your models here.


class Admin(models.Model):
    """管理员表"""
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)

    def __str__(self):
        return self.username


class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name='标题', max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """来访者表"""
    name = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户积分', max_digits=10, decimal_places=2, default=0)
    # create_time = models.DateTimeField(verbose_name='来访时间')
    create_time = models.DateField(verbose_name='来访时间')

    # 无约束
    # depart_id = models.BigIntegerField(verbose_name='部门id')

    # 1.有约束
    #   -to,与那张表关联
    #   -to_field,表中的那一列关联
    # 2.Django自动
    #   -写的depart
    #   -生成数据列 depart_id
    # 3.部门表被删除
    #  3.1 级联删除  on_delete=models.CASCADE  表示如果部门表被删除，旗下的部门表的来访者也被删除
    depart = models.ForeignKey(verbose_name='部门', to='Department', to_field='id', on_delete=models.CASCADE)
    #  3.2 置空  null=True, blank=True, on_delete=models.SET_NULL 表示如果部门表被删除，旗下的部门表的来访者部门位为空值
    # depart = models.ForeignKey(to='Department', to_field='id', null=True, blank=True, on_delete=models.SET_NULL)

    # 在Django中做的约束
    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)

    # def __str__(self):
    #     return self.name

callapps/views/account.py
"""
管理员 登录 注册 视图
"""

from django.shortcuts import render, redirect, HttpResponse
from callapps.utils.form import LoginForm, AdminModelForm
from callapps import models
from callapps.utils.code import check_code
from io import BytesIO


def login(request):
    """登录"""
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证码的校验
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', '')
        if code.upper() != user_input_code.upper():
            form.add_error('code', '验证码错误')
            return render(request, 'login.html', {'form': form})

        # 去数据库校验用户名和密码是否正确，获取用户对象 / None
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error('password', '用户名或密码错误')
            return render(request, 'login.html', {'form': form})

        # 用户名和密码正确
        # 网站生成随机字符串; 写到用户浏览器的cookie中；在写入到session中；
        request.session['info'] = {'id': admin_object.id, 'name': admin_object.username}

        # session可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)

        return redirect('/admin/list/')

    return render(request, 'login.html', {'form': form})


def image_code(request):
    """生成图片验证码"""

    # 调用pillow函数，生成图片
    img, code_string = check_code()

    # 写入到自己的session中（以便后续获取验证码再进行校验）
    request.session['image_code'] = code_string

    # 给session设置60s超时
    request.session.set_expiry(60)

    # 把图片写入到内存中
    stream = BytesIO()
    img.save(stream, 'png')

    return HttpResponse(stream.getvalue())


def logout(request):
    """注销"""
    request.session.clear()
    return redirect('/login/')


def register(request):
    """注册（添加管理员）"""

    if request.method == 'GET':
        form = AdminModelForm()
        return render(request, 'register.html', {'form': form})

    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/login/')
    return render(request, 'register.html', {'form': form})

callapps/views/admin.py
"""
管理员 视图
"""
from django.shortcuts import render, redirect
from callapps import models
from callapps.utils.pagination import Pagination
from callapps.utils.form import AdminModelForm, AdminEditModelForm, AdminResetModelForm


def admin_list(request):
    """管理员列表"""
    # 构造搜索条件
    data_dict = {}
    search_data = request.GET.get('q', '')
    if search_data:
        data_dict['username__contains'] = search_data

    # 根据搜索条件去数据库获取
    queryset = models.Admin.objects.filter(**data_dict)

    # 分页
    page_object = Pagination(request, queryset)

    context = {
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
        'search_data': search_data,
    }
    return render(request, 'admin_list.html', context)


def admin_add(request):
    """添加管理员"""
    title = '新建管理员'
    if request.method == 'GET':
        form = AdminModelForm
        return render(request, 'change.html', {'form': form, 'title': title})

    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form': form, 'title': title})


def admin_edit(request, nid):
    """编辑管理员"""
    # 对象 / None
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'error.html', {'msg': '数据不存在'})

    title = '编辑管理员'

    if request.method == 'GET':
        form = AdminEditModelForm(instance=row_object)
        return render(request, 'change.html', {'form': form, 'title': title})

    form = AdminEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form': form, 'title': title})


def admin_delete(request, nid):
    """删除管理员"""
    # 对象 / None
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'error.html', {'msg': '数据不存在'})

    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list/')


def admin_reset(request, nid):
    """重置管理员密码"""
    # 对象 / None
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'error.html', {'msg': '数据不存在'})

    title = "重置密码 - {}".format(row_object.username)

    if request.method == 'GET':
        form = AdminResetModelForm()
        return render(request, 'change.html', {'form': form, 'title': title})

    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'form': form, 'title': title})

callapps/views/avatar.py
from django.shortcuts import render, redirect
"""
更改头像 视图函数
"""


def avatar_edit(request):
    """更改头像"""
    if request.method == 'GET':
        return render(request, 'avatar_edit.html')

    file = request.FILES.get('avatar')
    file_name = 'media/avatar/'+file.name

    with open(file_name, 'wb+') as fo:
        for chunk in file.chunks():
            fo.write(chunk)

    # 将用户头像写到session
    info = request.session.get('info')
    request.session['info'] = {
        'id': info['id'],
        'name': info['name'],
        'avatar': '/'+file_name,
    }

    return redirect('/recognise/')

callapps/views/depart.py
"""
学院 视图函数
"""
from django.shortcuts import render, redirect
from callapps import models
from callapps.utils.pagination import Pagination  # 自定义的分页组件
from callapps.utils.form import DepartModelForm


def depart_list(request):
    """部门列表"""
    # 构造搜索条件
    # data_dict = {}
    # search_data = request.GET.get('q', '')
    # if search_data:
    #     data_dict['title__contains'] = search_data

    # 根据搜索条件去数据库获取
    # queryset = models.Admin.objects.filter(**data_dict)

    # 获取所有部门列表 [obj,obj,obj,]
    queryset = models.Department.objects.all()

    # 分页
    page_object = Pagination(request, queryset)

    context = {
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
        # 'search_data': search_data,
    }

    return render(request, 'depart_list.html', context)


def depart_add(request):
    """添加部门"""
    title = '添加部门'
    if request.method == 'GET':
        form = DepartModelForm
        return render(request, 'change.html', {"form": form, 'title': title})

    # 用户POST提交数据，数据校验
    form = DepartModelForm(data=request.POST)
    if form.is_valid():
        # 如果数据合法，保存到数据库
        form.save()
        return redirect('/depart/list/')

    # 校验失败，在页面上显示错误信息
    return render(request, 'change.html', {"form": form, 'title': title})


def depart_delete(request, nid):
    """删除部门"""
    models.Department.objects.filter(id=nid).delete()
    return redirect('/depart/list/')


def depart_edit(request, nid):
    """修改部门"""
    title = '修改部门'
    # 根据id去数据库获取要编辑的那一行数据（对象）
    row_object = models.Department.objects.filter(id=nid).first()

    if request.method == 'GET':
        form = DepartModelForm(instance=row_object)
        return render(request, 'change.html', {"form": form, 'title': title})

    form = DepartModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # 校验成功
        form.save()
        return redirect('/depart/list/')

    # 校验失败，提示错误信息
    return render(request, 'change.html', {"form": form, 'title': title})

callapps/views/recognise.py
from django.shortcuts import render


def link(request):
    return render(request, 'recognise.html')

callapps/views/runGUI.py
from django.shortcuts import render
import os


def run(request):
    os.system('python GUI.py')
    return render(request, 'call.html', {'text': '表情识别结束，感谢您的使用'})

callapps/views/user.py
"""
来访者 视图函数
"""
from django.shortcuts import render, redirect
from callapps import models
from callapps.utils.pagination import Pagination  # 自定义的分页组件
from callapps.utils.form import UserModelForm


def user_list(request):
    """来访者列表"""
    # 构造搜索条件
    # data_dict = {}
    # search_data = request.GET.get('q', '')
    # if search_data:
    #     data_dict['name__contains'] = search_data

    # 根据搜索条件去数据库获取
    # queryset = models.Admin.objects.filter(**data_dict)

    # 获取所有来访者列表 [obj,obj,obj,]
    queryset = models.UserInfo.objects.all()

    # 分页
    page_object = Pagination(request, queryset)

    context = {
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
        # 'search_data': search_data,
    }
    return render(request, 'user_list.html', context)


def user_add(request):
    """添加来访者（ModelForm版本）"""
    title = '添加来访者'
    if request.method == "GET":
        form = UserModelForm
        return render(request, 'user_change.html', {"form": form, 'title': title})

    # 用户POST提交数据，数据校验
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        # 如果数据合法，保存到数据库
        form.save()
        return redirect('/user/list/')

    # 校验失败，在页面上显示错误信息
    return render(request, 'user_change.html', {"form": form, 'title': title})


def user_edit(request, nid):
    """编辑来访者"""
    title = '编辑来访者'
    # 根据id去数据库获取要编辑的那一行数据（对象）
    row_object = models.UserInfo.objects.filter(id=nid).first()

    if request.method == "GET":
        form = UserModelForm(instance=row_object)
        return render(request, 'user_change.html', {"form": form, 'title': title})

    form = UserModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # 默认保存的是来访者输入的所有数据，如果想要再来访者输入以外增加一点值
        # form.instance.字段名 = 值
        form.save()
        return redirect('/user/list')
    return render(request, 'user_change.html', {"form": form, 'title': title})


def user_delete(request, nid):
    """删除来访者"""
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect('/user/list')

callapps/templates/admin_list.html
{% extends 'layout.html' %}

{% block title %}
    管理员列表
{% endblock title %}

{% block content %}
    <div class="container">

        {# 新建 搜索部分 #}
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    {#新建按钮#}
                    <a class="btn btn-success navbar-btn" href="/admin/add/">
                        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                        新建管理员
                    </a>
                </div>

                {# 搜索部分 #}
                <div style="float: right">
                    <form class="navbar-form navbar-left">
                        <div class="form-group">
                            <input type="text" class="form-control " placeholder="请输入用户名" name="q"
                                   value="{{ search_data }}">
                        </div>
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            查找
                        </button>
                    </form>
                </div>
            </div>
        </nav>

        {#面板#}
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                管理员列表
            </div>

            <!-- Table -->
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>ID</th>
                    <th>用户名</th>
                    <th>密码</th>
                    <th>重置密码</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.username }}</td>
                        <td>******</td>
                        <td><a href="/admin/{{ obj.id }}/reset/">重置密码</a></td>
                        <td>
                            <a href="/admin/{{ obj.id }}/edit" class="btn btn-primary btn-xs">编辑</a>
                            <a href="/admin/{{ obj.id }}/delete" class="btn btn-danger btn-xs">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {# 分页 #}
        <ul class='pagination'>
            {{ page_string }}
        </ul>

    </div>
{% endblock content %}

callapps/templates/avatar_edit.html
{% extends 'layout.html' %}

{% block title %}
    更改头像
{% endblock title %}

{% block content %}
    <div class="container">
        {#面板#}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">更改头像</h3>
            </div>
            <div class="panel-body">
                {#表单#}
                <form method="post" novalidate enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="avatar">
                    <br>
                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

callapps/templates/call.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>表情识别</title>
</head>
<body>
 <div>
     {{text}}
 </div>

</body>
</html>

callapps/templates/change.html
{# 公共html模板， 用于 添加 或者 修改 页面， 文件上传除外#}

{% extends 'layout.html' %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block content %}
    <div class="container">
        {#面板#}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                {#表单#}
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for obj in form %}
                        <div class="form-group">
                            <label>{{ obj.label }}</label>
                            {{ obj }}
                            <span style="color: red">{{ obj.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

callapps/templates/depart_list.html
{% extends 'layout.html' %}

{% block title %}
    部门列表
{% endblock title %}

{% block content %}
    <div class="container">
        {# 新建 搜索部分 #}
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    {#新建按钮#}
                    <a class="btn btn-success navbar-btn" href="/depart/add/">
                        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                        新建部门
                    </a>
                </div>

                {# 搜索部分 #}
                <div style="float: right">
                    <form class="navbar-form navbar-left">
                        <div class="form-group">
                            <input type="text" class="form-control " placeholder="请输入部门名称" name="q"
                                   value="{{ search_data }}">
                        </div>
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            查找
                        </button>
                    </form>
                </div>
            </div>
        </nav>

        {#面板#}
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                部门列表
            </div>

            <!-- Table -->
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>ID</th>
                    <th>名称</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.title }}</td>
                        <td>
                            <a href="/depart/{{ obj.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                            <a href="/depart/{{ obj.id }}/delete/" class="btn btn-danger btn-xs">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {# 分页 #}
        <ul class='pagination'>
            {{ page_string }}
        </ul>
    </div>
{% endblock content %}

callapps/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>
{% endblock content %}

callapps/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
    {% block css %}{% endblock css %}

    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
</head>
<body>
{#导航部分#}
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">心理咨询表情识别辅助系统</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                <li><a href="/recognise/">表情识别</a></li>
                <li><a href="/admin/list/">管理员账户</a></li>
                <li><a href="/depart/list/">部门管理</a></li>
                <li><a href="/user/list/">来访者管理</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/login/">登录</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        {{ request.session.info.name }}
                        <img src="{{ request.session.info.avatar | default:'/media/avatar/2.jpg' }}" style="height: 25px;border-radius: 50%;width: 25px">
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">个人信息</a></li>
                        <li><a href="#">我的信息</a></li>
                        <li><a href="/avatar/edit/">更改头像</a></li>

                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{#内容区#}
<div>
    {% block content %}{% endblock content %}
</div>

<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.js' %}"></script>
{% block js %} {% endblock js %}
</body>
</html>

callapps/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <!--引入bootstrap核心样式-->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2 class="red-text" style="color: #ff00d5;">心理咨询表情识别辅助系统</h2>
    <h2>管理员登录</h2>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: #ff0000">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px">
                </div>
            </div>
        </div>
        <input type="submit" value="登录" class="btn btn-primary">
        <div>
            <br>
            <a href="/register/" class="btn-link">没有账户？去注册</a>
        </div>



    </form>
</div>

<!--引入jquery核心js文件-->
<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
<!--引入bootstrap核心js文件-->
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

callapps/templates/recognise.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        table, th, td {
            text-align: center;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="container">
        <div style="margin-bottom: 20px">
            <input type="button" value="表情识别" class="btn btn-success" onclick="window.location.href='/call/'"> {# 点击按钮打开GUI #}
        </div>
    <p>请告知来访者摘下<mark>眼镜和口罩等，露出整个面部</mark> 识别效果更佳</p>
    </div>
{% endblock content %}

callapps/templates/user_change.html
{% extends 'layout.html' %}

{% block title %}
    {{ title }}
{% endblock title %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker-1.9.0/css/bootstrap-datepicker.css' %}">
{% endblock css %}

{% block content %}
    <div class="container">
        {#面板#}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                {#表单#}
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for obj in form %}
                        <div class="form-group">
                            <label>{{ obj.label }}</label>
                            {{ obj }}
                            <span style="color: red">{{ obj.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker-1.9.0/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker-1.9.0/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function (){
            $('#id_create_time').datepicker({
                format : 'yyyy-mm-dd',
                startDate : '0',
                language : 'zh-CN',
                autoclose : true
            });
        })
    </script>
{% endblock js %}

callapps/templates/user_list.html
{% extends 'layout.html' %}

{% block title %}
    用户列表
{% endblock title %}

{% block content %}
    <div class="container">

        {# 新建 搜索部分 #}
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    {#新建按钮#}
                    <a class="btn btn-success navbar-btn" href="/user/add/">
                        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                        新建来访者
                    </a>
                </div>

                {# 搜索部分 #}
                <div style="float: right">
                    <form class="navbar-form navbar-left">
                        <div class="form-group">
                            <input type="text" class="form-control " placeholder="请输入来访者姓名" name="q"
                                   value="{{ search_data }}">
                        </div>
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            查找
                        </button>
                    </form>
                </div>
            </div>
        </nav>

        {#面板#}
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                来访者列表
            </div>

            <!-- Table -->
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>账户积分</th>
                    <th>来访时间</th>
                    <th>性别</th>
                    <th>所属部门</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.password }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.account }}</td>
                        <td>{{ obj.create_time | date:"Y-m-d" }}</td>
                        <td>{{ obj.get_gender_display }}</td>
                        <td>{{ obj.depart.title }}</td>
                        <td>
                            <a href="/user/{{ obj.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                            <a href="/user/{{ obj.id }}/delete/" class="btn btn-danger btn-xs">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {# 分页 #}
        <ul class='pagination'>
            {{ page_string }}
        </ul>
    </div>
{% endblock content %}